version: '3.4'

services:


  rabbitmessage.api:
    image: ${DOCKER_REGISTRY-}rabbitmessageapi
    build:
      context: .
      dockerfile: RabbitMessage.API/Dockerfile


  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    ports:
     - '5672:5672'
     - '8080:15672'
